### ISSUE TITLE
digmill markdownify use broken

### ISSUE THREAD

**Issue by balmas** [perseids-project/perseids-client-apps#20]
I'm not sure if this was taken out intentionally, or something that got lost when the code was merged.  The annotation/enter.html looks like it has classes from the [markdownify library](https://github.com/tibastral/markdownify) to enable a widget for entering links into the commentary.

I tried adding it in, but the display gets really wonky then. Needs some effort to fix.

This is currenly only in the digmill branch of this code.

**Comment by annakrohn** [comment]
I believe I removed this initially because of a conflict with Typeahead.

Jquery versions are probably the culprit.  Markdownify has a dependency of 2.1.1 (https://github.com/tibastral/markdownify/blob/master/bower.json).  When 2.1.1 is explicitly loaded Typeahead no longer works, we're loading 1.10.2 (https://github.com/perseids-project/perseids-client-apps/blob/master/app/templates/alignment/enter.html#L27).  Meanwhile capitains-sparrow.typeahead has 2.1.3 as s dependency (https://github.com/Capitains/jQuery.typeahead/blob/master/bower.json).

**Comment by annakrohn** [comment]
@balmas, everything appears to be working fine now with commit 6297501060448590597a334c3f17f46a42c917c8?  I changed the jquery version to 2.1.1, typeahead seems to work just fine, and removing a second markdownify function definition got rid of other weirdness.

**Comment by balmas** [comment]
ok, great.  if it works, then I say go with it.

**Comment by annakrohn** [comment]
Merged with the viewsclean branch.
